site_name: "Cailey's Artifactory Documentation"
site_description: "Some docs written by me about Artifactory"
docs_dir: "docs"
repo_url:  ""
edit_uri: edit/main/docs/
plugins:
    - techdocs-core
    - ezlinks
markdown_extensions:
    - markdown_inline_mermaid
    - md_in_html
    -   mkpatcher:
            location: patcher.py
